import React from 'react';
import {
  View,
    Text,
      FlatList,
        TouchableOpacity,
          Image,
            StyleSheet,
              Linking,
                Alert
                } from 'react-native';
                import Icon from 'react-native-vector-icons/MaterialIcons';

                const CartScreen = ({ route, navigation }) => {
                  const { cart } = route.params || { cart: [] };

                    const calculateTotal = () => {
                        return cart.reduce((total, item) => total + item.price, 0);
                          };

                            const sendWhatsAppOrder = () => {
                                if (cart.length === 0) {
                                      Alert.alert('Panier vide', 'Votre panier est vide. Ajoutez des produits avant de commander.');
                                            return;
                                                }

                                                    let message = `Bonjour MUCO SHOP! Je souhaite commander les produits suivants:\n\n`;
                                                        
                                                            cart.forEach((item, index) => {
                                                                  message += `*${index + 1}. ${item.name}* - ${item.price.toLocaleString()} FBU\n`;
                                                                      });
                                                                          
                                                                              message += `\n*Total: ${calculateTotal().toLocaleString()} FBU*\n\n`;
                                                                                  message += `Merci de me contacter pour finaliser la commande.`;

                                                                                      const url = `whatsapp://send?phone=+25767301044&text=${encodeURIComponent(message)}`;
                                                                                          
                                                                                              Linking.openURL(url).catch(() => {
                                                                                                    Alert.alert('Erreur', 'WhatsApp n\'est pas installé sur votre appareil');
                                                                                                        });
                                                                                                          };

                                                                                                            const renderCartItem = ({ item, index }) => (
                                                                                                                <View style={styles.cartItem}>
                                                                                                                      <Image source={{ uri: item.image }} style={styles.cartItemImage} />
                                                                                                                            <View style={styles.cartItemInfo}>
                                                                                                                                    <Text style={styles.cartItemName}>{item.name}</Text>
                                                                                                                                            <Text style={styles.cartItemPrice}>{item.price.toLocaleString()} FBU</Text>
                                                                                                                                                  </View>
                                                                                                                                                      </View>
                                                                                                                                                        );

                                                                                                                                                          return (
                                                                                                                                                              <View style={styles.container}>
                                                                                                                                                                    {cart.length === 0 ? (
                                                                                                                                                                            <View style={styles.emptyCart}>
                                                                                                                                                                                      <Icon name="shopping-cart" size={80} color="#ccc" />
                                                                                                                                                                                                <Text style={styles.emptyCartText}>Votre panier est vide</Text>
                                                                                                                                                                                                          <TouchableOpacity 
                                                                                                                                                                                                                      style={styles.shopButton}
                                                                                                                                                                                                                                  onPress={() => navigation.navigate('Home')}
                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                        <Text style={styles.shopButtonText}>Commencer vos achats</Text>
                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                  <FlatList
                                                                                                                                                                                                                                                                                                              data={cart}
                                                                                                                                                                                                                                                                                                                          renderItem={renderCartItem}
                                                                                                                                                                                                                                                                                                                                      keyExtractor={(item, index) => index.toString()}
                                                                                                                                                                                                                                                                                                                                                  style={styles.cartList}
                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                <View style={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.totalContainer}>
                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.totalLabel}>Total:</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.totalAmount}>{calculateTotal().toLocaleString()} FBU</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <TouchableOpacity 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={styles.orderButton}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPress={sendWhatsAppOrder}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Icon name="whatsapp" size={24} color="white" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.orderButtonText}>Commander via WhatsApp</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#f5f5f5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emptyCart: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emptyCartText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                shopButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#007bff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingHorizontal: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    shopButtonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cartList: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cartItem: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginHorizontal: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginVertical: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cartItemImage: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: 60,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: 60,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginRight: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cartItemInfo: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cartItemName: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '600',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cartItemPrice: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#007bff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        footer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderTopWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderTopColor: '#eee',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalLabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '600',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalAmount: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#007bff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        orderButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#25D366',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    orderButtonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginLeft: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default CartScreen;
