import React from 'react';
import {
  View,
    Text,
      Image,
        ScrollView,
          TouchableOpacity,
            StyleSheet,
              Linking
              } from 'react-native';
              import Icon from 'react-native-vector-icons/MaterialIcons';

              const ProductScreen = ({ route, navigation }) => {
                const { product } = route.params;

                  const sendWhatsAppOrder = () => {
                      const message = `Bonjour MUCO SHOP! Je suis intéressé par le produit suivant:\n\n*${product.name}*\nPrix: ${product.price.toLocaleString()} FBU\n\nDescription: ${product.description}\n\nJe souhaite commander ce produit.`;
                          const url = `whatsapp://send?phone=+25767301044&text=${encodeURIComponent(message)}`;
                              
                                  Linking.openURL(url).catch(() => {
                                        alert('WhatsApp n\'est pas installé sur votre appareil');
                                            });
                                              };

                                                return (
                                                    <ScrollView style={styles.container}>
                                                          <Image source={{ uri: product.image }} style={styles.productImage} />
                                                                
                                                                      <View style={styles.productDetails}>
                                                                              <Text style={styles.productName}>{product.name}</Text>
                                                                                      <Text style={styles.productPrice}>{product.price.toLocaleString()} FBU</Text>
                                                                                              
                                                                                                      <View style={styles.categoryContainer}>
                                                                                                                <Text style={styles.category}>{product.category}</Text>
                                                                                                                        </View>
                                                                                                                                
                                                                                                                                        <Text style={styles.descriptionTitle}>Description</Text>
                                                                                                                                                <Text style={styles.description}>{product.description}</Text>
                                                                                                                                                        
                                                                                                                                                                <TouchableOpacity style={styles.whatsappButton} onPress={sendWhatsAppOrder}>
                                                                                                                                                                          <Icon name="whatsapp" size={24} color="white" />
                                                                                                                                                                                    <Text style={styles.whatsappButtonText}>Commander via WhatsApp</Text>
                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                    
                                                                                                                                                                                                            <View style={styles.features}>
                                                                                                                                                                                                                      <View style={styles.feature}>
                                                                                                                                                                                                                                  <Icon name="local-shipping" size={20} color="#007bff" />
                                                                                                                                                                                                                                              <Text style={styles.featureText}>Livraison rapide</Text>
                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                  <View style={styles.feature}>
                                                                                                                                                                                                                                                                              <Icon name="security" size={20} color="#007bff" />
                                                                                                                                                                                                                                                                                          <Text style={styles.featureText}>Paiement sécurisé</Text>
                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                              <View style={styles.feature}>
                                                                                                                                                                                                                                                                                                                          <Icon name="support-agent" size={20} color="#007bff" />
                                                                                                                                                                                                                                                                                                                                      <Text style={styles.featureText}>Support 24/7</Text>
                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                                                                                                                  </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                    const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                      container: {
                                                                                                                                                                                                                                                                                                                                                                          flex: 1,
                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                  productImage: {
                                                                                                                                                                                                                                                                                                                                                                                      width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                          height: 300,
                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                              productDetails: {
                                                                                                                                                                                                                                                                                                                                                                                                  padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                      productName: {
                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 24,
                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#333',
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                          productPrice: {
                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#007bff',
                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                              categoryContainer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#f8f9fa',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      paddingHorizontal: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          paddingVertical: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alignSelf: 'flex-start',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      descriptionTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: '600',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  lineHeight: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              whatsappButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#25D366',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              whatsappButtonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginLeft: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  features: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderTopWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderTopColor: '#eee',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paddingTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  feature: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  featureText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginLeft: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default ProductScreen;
